# Reglas de Asociación 🛒

!pip3 install mlxtend
!pip3 install kagglehub

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="jupyter_client.session")

## Descargar un dataset desde Kaggle

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shazadudwadia/supermarket")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/shazadudwadia/supermarket/1.archive...

100%|██████████| 323/323 [00:00<00:00, 627kB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/shazadudwadia/supermarket/versions/1

In [ ]:
foo = path + "/GroceryStoreDataSet.csv"

print(foo)

/root/.cache/kagglehub/datasets/shazadudwadia/supermarket/versions/1/GroceryStoreDataSet.csv

In [ ]:
df = pd.read_csv(foo, names = ['products'], sep = ',')
data = list(df["products"].apply(lambda x:x.split(",") ))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

## Vamos a usar one hot encoding para codificar las transacciones en vectores

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

a = TransactionEncoder()
a_data = a.fit(data).transform(data)
df = pd.DataFrame(a_data,columns=a.columns_)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

## Aplicar el algoritmo apriori con MinSupp = 0.2 para encontrar itemsets frecuentes

In [ ]:
df = apriori(df, min_support = 0.2, use_colnames = True, verbose = 1)
df

Processing 42 combinations | Sampling itemset size 3

    support              itemsets
0      0.35             (BISCUIT)
1      0.20           (BOURNVITA)
2      0.65               (BREAD)
3      0.40              (COFFEE)
4      0.30          (CORNFLAKES)
5      0.25               (MAGGI)
6      0.25                (MILK)
7      0.30               (SUGER)
8      0.35                 (TEA)
9      0.20      (BISCUIT, BREAD)
10     0.20         (MILK, BREAD)
11     0.20        (SUGER, BREAD)
12     0.20          (TEA, BREAD)
13     0.20  (CORNFLAKES, COFFEE)
14     0.20       (SUGER, COFFEE)
15     0.20          (MAGGI, TEA)

## Fijar MinConf para buscar las reglas a partir de estos itemsets frecuentes

In [ ]:
df_ar = association_rules(df, metric = "confidence", min_threshold = 0.5)
df_ar[['antecedents','consequents','support','confidence']]

    antecedents   consequents  support  confidence
0     (BISCUIT)       (BREAD)      0.2    0.571429
1        (MILK)       (BREAD)      0.2    0.800000
2       (SUGER)       (BREAD)      0.2    0.666667
3         (TEA)       (BREAD)      0.2    0.571429
4  (CORNFLAKES)      (COFFEE)      0.2    0.666667
5      (COFFEE)  (CORNFLAKES)      0.2    0.500000
6       (SUGER)      (COFFEE)      0.2    0.666667
7      (COFFEE)       (SUGER)      0.2    0.500000
8       (MAGGI)         (TEA)      0.2    0.800000
9         (TEA)       (MAGGI)      0.2    0.571429

# Actividad

Usando el algoritmo **apriori**, haga lo siguiente:

* Codifique las transacciones usando one hot encodings.
* Dibuje una curva MinSupp contra Número de itemsets frecuentes encontrados en los rangos `min_support = [0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]`
* Seleccione un valor de MinSupp. Luego busque reglas interesantes ajustando el umbral de confianza. Ajústelo de manera que encuentre al menos 7 reglas.
* Cuanto termine, me avisa para marcarlo como logrado.
* Pueden trabajar de a dos o tres.

In [ ]:
import pandas as pd
import numpy as np
import kagglehub
import matplotlib.pyplot as plt


# Download latest version
path = kagglehub.dataset_download("mashlyn/online-retail-ii-uci")

print("Path to dataset files:", path)

foo = path + '/online_retail_II.csv'

df = pd.read_csv(foo, encoding="latin1")

# Cada fila es un ítem en una transacción. Para agrupar por transacción:
data = df.groupby("Invoice")["StockCode"].apply(list).tolist()
data = data[:40000]

Using Colab cache for faster access to the 'online-retail-ii-uci' dataset.
Path to dataset files: /kaggle/input/online-retail-ii-uci